WebAssgn_team06/Models/Competition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAssgn_team06.Models
{
    public class Competition : IValidatableObject
    {
        [Display(Name = "ID")]
        public int CompetitionId { get; set; }

        
        [Display(Name = "Area of Interest")]
        public int AreaInterestId { get; set; }

        [Required(ErrorMessage = "Please enter a name!")]
        [Display(Name = "Name of competition")]
        [StringLength(255, ErrorMessage = "Name cannot exceed 255 characters")]
        public string CompetitionName { get; set; }

        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Result Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime ResultReleasedDate { get; set; }



        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            var end = new[] { "EndDate" };

            if (EndDate < StartDate)
            {
                yield return new ValidationResult("End Date must be greater than Start Date", end);

            }
            var result = new[] { "ResultReleasedDate" };
            if (ResultReleasedDate < EndDate)
            {
                yield return new ValidationResult("Result released date must be greater than End Date", result);
            }

        }



    }
}

WebAssgn_team06/Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssgn_team06.DAL;
using WebAssgn_team06.Models;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace WebAssgn_team06.Controllers
{
    public class CompetitionController : Controller
    {
        private CompetitionDAL cContext = new CompetitionDAL();
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();

        private CriteriaDAL criteriaContext = new CriteriaDAL();
        // GET: CompetitionController
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Competition> cList = cContext.GetAllCompetition();
            return View(cList);
        }

        // GET: CompetitionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CompetitionController/Create
        public ActionResult Create()
        {
            // Stop accessing the action if not logged in
            // or account not in the "admin" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["AreaInterestList"] = GetAreaInterest();
            return View();
        }
        private List<AreaInterest> GetAreaInterest()
        {
            // Get a list of area interest from database
            List<AreaInterest> areaInterestList = areaInterestContext.GetAllAreaInterest();

            return areaInterestList;
        }



        // POST: CompetitionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Competition c)
        {
            //Get country list for drop-down list
            //in case of the need to return to Create.cshtml view
            ViewData["AreaInterestList"] = GetAreaInterest();
            if (ModelState.IsValid)
            {
                //Add staff record to database
                c.CompetitionId = cContext.Add(c);
                //Redirect user to Competition/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(c);
            }
        }

        // GET: CompetitionController/CreateCriteria
        public ActionResult CreateCriteria()
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role

            //here edit!!
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            //To access competition list
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Competitor"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["CompetitionList"] = cContext.GetAllCompetition();

            return View();

        }

        //Xuan Qing
        //// POST: CompetitionController/CreateCriteria
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult CreateCriteria(CriteriaViewModel cvm)
        //{
        //    // Get competition list for drop - down list
        //    //in case of the need to return to Create.cshtml view
        //    ViewData["CompetitionList"] = cContext.GetAllCompetition();

        //    if (ModelState.IsValid)
        //    {
        //        //save your Model1 data
        //        foreach (Criteria criteria in cvm.Criterias)
        //        {
        //            cvm.Criterias.Add(criteria);
        //            //Save your SubItems here
        //            //Add criteria record to database
        //            criteria.CriteriaId = criteriaContext.Add(criteria);
        //        }

        //        //Redirect user to Staff/Index view
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        //Input validation fails, return to the Create view
        //        //to display error message
        //        return View();
        //    }
        //}

        // GET: CompetitionController/Edit/5
        public ActionResult Edit(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "admin" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            ViewData["AreaInterestList"] = GetAreaInterest();
            Competition c = cContext.GetDetails(id.Value);
            if (c == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(c);
        }

        // POST: CompetitionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Competition c)
        {
            ViewData["AreaInterestList"] = GetAreaInterest();
            if (cContext.HasCompetitor(c.CompetitionId) == false)
            {
                if (ModelState.IsValid)
                {
                    //Update competition record to database
                    cContext.Update(c);
                    return RedirectToAction("Index");
                }
                else
                {
                    //Input validation fails, return to the view
                    //to display error message
                    return View(c);
                }
            }
            else
            {
                //validation message
                String errorMsg = "Competition has competitors joined. Unable to edit competition.";
                ViewBag.validation = errorMsg;
                return View();
            }

        }

        // GET: CompetitionController/Delete/5
        public ActionResult Delete(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "admin" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            Competition c = cContext.GetDetails(id.Value);
            if (c == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(c);
        }

        // POST: CompetitionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Competition c)
        {
            if (cContext.HasCompetitor(c.CompetitionId) == false)
            {
                // Delete the competition record from database
                cContext.Delete(c.CompetitionId);
                return RedirectToAction("Index");
            }
            else
            {
                //validation message
                String errorMsg = "Competition has competitors joined. Unable to delete competition.";
                ViewBag.validation = errorMsg;
                return View();
            }
        }
    }
}

WebAssgn_team06/Views/Competition/Create.cshtml
@model WebAssgn_team06.Models.Competition

@{
    ViewData["Title"] = "Create";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Competition</title>
    <style type="text/css">
        body {
            /* background-color: rgba(0, 0, 255, 0.1);*/
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }

        .btn {
            box-sizing: border-box;
            background-color: transparent;
            border: 2px solid #5D18C5;
            border-radius: 0.6em;
            color: #5D18C5;
            cursor: pointer;
            display: flex;
            align-self: center;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1;
            margin: 20px;
            padding: 1.2em 2.8em;
            text-decoration: none;
            text-align: center;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 700;
        }

            .btn:hover, .btn:focus {
                color: #000;
                outline: 0;
            }

        .third {
            border-color: #5D18C5;
            color: #fff;
            box-shadow: 0 0 40px 40px #5D18C5 inset, 0 0 0 0 #5D18C5;
            transition: all 150ms ease-in-out;
        }

            .third:hover {
                box-shadow: 0 0 10px 0 #5D18C5 inset, 0 0 10px 4px #5D18C5;
            }

        .every {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            align-items: center;
            align-content: center;
            align-self: center;
        }

        .FormContent {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
        }
    </style>
</head>

<body>
    <h4 class="PageTitle">Add Competition Record</h4>
    <hr />
    <form asp-action="Create">
        @Html.ValidationSummary(true)
        <fieldset class="FormContent">
            <div class="form-group row">
                <label asp-for="CompetitionName"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="CompetitionName" class="form-control" />
                    <span asp-validation-for="CompetitionName"
                          class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="AreaInterestId"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <select asp-for="AreaInterestId"
                            asp-items="@(new SelectList(
                                @ViewData["AreaInterestList"] as List <AreaInterest>,
                                "AreaInterestId", "Name"))"
                            class="form-control" id="areaSel"></select>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="StartDate"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input type="datetime-local" asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="EndDate"
                          class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="EndDate"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input type="datetime-local" asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate"
                          class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="ResultReleasedDate"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input type="datetime-local" asp-for="ResultReleasedDate" class="form-control" />
                    <span asp-validation-for="ResultReleasedDate"
                          class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-9 offset-sm-3">
                    <input id="submitBtn " type="submit" value="Create"
                           class="btn third" />
                </div>
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </fieldset>
    </form>

</body>

</html>

WebAssgn_team06/Views/Competition/CreateCriteria.cshtml
@model WebAssgn_team06.Models.CriteriaViewModel

@{
    ViewData["Title"] = "CreateCriteria";
}

<!--<h4 class="PageTitle">Add Criteria</h4>
<hr />
<form asp-action="CreateCriteria">
    <fieldset class="FormContent">
        <div class="form-group row">
            <a href="#" id="add">Add</a>
            <label asp-for="CompetitionId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">-->
                @*<input asp-for="CompetitionId" class="form-control" />*@
                <!--<select asp-for="CompetitionId"
                        asp-items="@(new SelectList(
                                @ViewData["CompetitionList"] as List <Competition>,
                                "CompetitionId", "CompetitionName"))"
                        class="form-control"></select>
                <span asp-validation-for="CompetitionId"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Criterias[0].CriteriaName"
                   class="col-sm-3 col-form-label items"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Criterias[0].CriteriaName" class="form-control" />
                <span asp-validation-for="Criterias[0].CriteriaName"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Criterias[0].Weightage"
                   class="col-sm-3 col-form-label items"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Criterias[0].Weightage" class="form-control" />
                <span asp-validation-for="Criterias[0].Weightage"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row" id="item-list">
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>


@section Scripts {
    <script>
        $(function () {
            $("#add").click(function (e) {
                e.preventDefault();
                var i = ($(".items").length) / 2;
                //var n = '<br/>' + '<input type="text" class="items" name="users[' + i + '].FirstName" />' +
                    //'<input type="text" class="items" name="users[' + i + '].LastName" />';
                var n = `<div class="form-group row">
            <label asp-for="Criterias[` + i + `].CriteriaName"
                   class="col-sm-3 col-form-label items"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Criterias[` + i + `].CriteriaName" class="form-control" />
                <span asp-validation-for="Criterias[` + i + `].CriteriaName"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Criterias[` + i + `].Weightage"
                   class="col-sm-3 col-form-label items"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Criterias[` + i + `].Weightage" class="form-control" />
                <span asp-validation-for="Criterias[` + i + `].Weightage"
                      class="text-danger"></span>
            </div>
        </div>`;


                $("#item-list").append(n);
            });

        });
    </script>
}-->

WebAssgn_team06/Views/Competition/Delete.cshtml
@model WebAssgn_team06.Models.Competition

@{
    ViewData["Title"] = "Delete";
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete competition</title>
    <style type="text/css">
        body {
            /* background-color: rgba(0, 0, 255, 0.1);*/
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }

        .btn {
            box-sizing: border-box;
            background-color: transparent;
            border: 2px solid #5D18C5;
            border-radius: 0.6em;
            color: #5D18C5;
            cursor: pointer;
            display: flex;
            align-self: center;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1;
            margin: 20px;
            padding: 1.2em 2.8em;
            text-decoration: none;
            text-align: center;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 700;
        }

            .btn:hover, .btn:focus {
                color: #000;
                outline: 0;
            }

        .third {
            border-color: #5D18C5;
            color: #fff;
            box-shadow: 0 0 40px 40px #5D18C5 inset, 0 0 0 0 #5D18C5;
            transition: all 150ms ease-in-out;
        }

            .third:hover {
                box-shadow: 0 0 10px 0 #5D18C5 inset, 0 0 10px 4px #5D18C5;
            }

        .every {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            align-items: center;
            align-content: center;
            align-self: center;
        }

        .FormContent {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
        }
    </style>
</head>
<h4 class="PageTitle">Delete Competition Record</h4>
<hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="CompetitionId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionId" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn third" />
            </div>

        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <span class="text-danger">@ViewBag.validation</span>
            </div>

        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WebAssgn_team06/Views/Competition/Edit.cshtml
@model WebAssgn_team06.Models.Competition

@{
    ViewData["Title"] = "Edit";
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Competition</title>
    <style type="text/css">
        body {
            /* background-color: rgba(0, 0, 255, 0.1);*/
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }

        .btn {
            box-sizing: border-box;
            background-color: transparent;
            border: 2px solid #5D18C5;
            border-radius: 0.6em;
            color: #5D18C5;
            cursor: pointer;
            display: flex;
            align-self: center;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1;
            margin: 20px;
            padding: 1.2em 2.8em;
            text-decoration: none;
            text-align: center;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 700;
        }

            .btn:hover, .btn:focus {
                color: #000;
                outline: 0;
            }

        .third {
            border-color: #5D18C5;
            color: #fff;
            box-shadow: 0 0 40px 40px #5D18C5 inset, 0 0 0 0 #5D18C5;
            transition: all 150ms ease-in-out;
        }

            .third:hover {
                box-shadow: 0 0 10px 0 #5D18C5 inset, 0 0 10px 4px #5D18C5;
            }

        .every {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            align-items: center;
            align-content: center;
            align-self: center;
        }

        .FormContent {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
        }
    </style>
</head>
<h4 class="PageTitle">Edit Competition Record</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CompetitionId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionId" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" class="form-control" />
                <span asp-validation-for="CompetitionName"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="AreaInterestId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="AreaInterestId"
                        asp-items="@(new SelectList(
                                @ViewData["AreaInterestList"] as List <AreaInterest>,
                                "AreaInterestId", "Name"))"
                        class="form-control"></select>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="StartDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input type="datetime-local" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EndDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input type="datetime-local" asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ResultReleasedDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input type="datetime-local" asp-for="ResultReleasedDate" class="form-control" />
                <span asp-validation-for="ResultReleasedDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Edit"
                       class="btn third" />
            </div>

        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <span class="text-danger">@ViewBag.validation</span>
            </div>

        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WebAssgn_team06/Views/Competition/Index.cshtml
@model IEnumerable<WebAssgn_team06.Models.Competition>

@{
    ViewData["Title"] = "View Competition";
}


<h4 class="PageTitle"></h4>

<p><a asp-action="Create">Create New Competition</a></p>
<!-- Add a partial view to display a list of records
 in a tabular format. -->
<partial name="~/Views/Competition/_ViewCompetition.cshtml" model="@Model" />

WebAssgn_team06/Views/Competition/_ViewCompetition.cshtml
@model IEnumerable<WebAssgn_team06.Models.Competition>

@if (Model.ToList().Count > 0)
{
    <style>
        .ViewCompetitionBox {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
            padding: 10px;
            margin: auto;
            width: 95%;
            border-radius: 15px;
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }
    </style>
    <div class="ViewCompetitionBox">
        <hr class="new1">
        <br />
        <br />
        <h4 class="PageTitle">View Competitions</h4>
        <br />
        <br />
       
        <br />
        <br />
        <div class="table-responsive">
            <table id="viewStaff" class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Competition ID</th>
                        <th>AreaInterest ID</th>
                        <th>Competition Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Result Released Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.CompetitionId.ToString()</td>
                            <td>@item.AreaInterestId.ToString()</td>
                            <td>@item.CompetitionName</td>

                            <td>@item.StartDate</td>
                            <td>@item.EndDate</td>
                            <td>@item.ResultReleasedDate</td>
                            <td>
                                <a asp-action="Edit" asp-controller="Competition"
                                   asp-route-id="@item.CompetitionId">Edit</a> |

                                <a asp-action="Delete" asp-controller="Competition"
                                   asp-route-id="@item.CompetitionId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

}
else
{
    <span style="color:red">No record found!</span>
}