WebAssgn_team06/Models/CompetitionJudge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WebAssgn_team06.Models
{
    public class CompetitionJudge
    {
        //pk, fk-> Competition (CompetitionID)
        [Display(Name = "Competition ID")]
        public int CompetitionId { get; set; }
        [Display(Name = "Competition Name")]
        public String CompetitionName { get; set; }

        //pk, fk-> Judge (JudgeID)
        [Display(Name = "Judge ID")]
        public int JudgeId { get; set; }
        [Display(Name = "Judge Name")]
        public String JudgeName { get; set; }

    }
}

WebAssgn_team06/Controllers/CompetitionJudgeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssgn_team06.DAL;
using WebAssgn_team06.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;

namespace WebAssgn_team06.Controllers
{
    public class CompetitionJudgeController : Controller
    {
        private CompetitionJudgeDAL cjContext = new CompetitionJudgeDAL();
        private CompetitionDAL cContext = new CompetitionDAL();
        private JudgeDAL jContext = new JudgeDAL();
        // GET: competitionjudgeController
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<CompetitionJudge> cjList = cjContext.GetAllCompetitionJudge();
            return View(cjList);
        }
        public ActionResult Create()
        {
            // Stop accessing the action if not logged in
            // or account not in the "Admin" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["CompetitionList"] = GetCompetition();
            ViewData["JudgeList"] = GetJudge();

            return View();
        }

        private List<Competition> GetCompetition()
        {
            // Get a list of competition from database
            List<Competition> competitionList = cContext.GetAllCompetition();
            // Adding a select prompt at the first row of the competition list
            competitionList.Insert(0, new Competition
            {
                CompetitionId = 0,
                CompetitionName = "--Select--"
            });
            return competitionList;
        }
        private List<Judge> GetJudge()
        {
            // Get a list of judge from database
            List<Judge> judgeList = jContext.GetAllJudge();
            // Adding a select prompt at the first row of the judge list
            judgeList.Insert(0, new Judge
            {
                JudgeId = 0,
                JudgeName = "--Select--"
            });
            return judgeList;
        }

        // POST: Staff/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompetitionJudge cj)
        {
            //Get country list for drop-down list
            //in case of the need to return to Create.cshtml view
            ViewData["CompetitionList"] = GetCompetition();
            ViewData["JudgeList"] = GetJudge();

            if (ModelState.IsValid)
            {
                if (cjContext.judgeAssigned(cj.JudgeId) == false)
                {
                    if (cjContext.beforeEndDate(cj.CompetitionId) == true)
                    {

                        //Add competition judge record to database
                        cj.CompetitionId = cjContext.Add(cj);
                        cj.JudgeId = cjContext.Add(cj);
                        //Redirect user to Index view
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        //validation message
                        String errorMsg = "The End Date of competition has passed. Unable to add judge.";
                        ViewBag.validation = errorMsg;
                        return View();
                    }
                }
                else
                {
                    //validation message
                    String errorMsg = "Judge already assigned. Unable to add judge.";
                    ViewBag.validation = errorMsg;
                    return View();
                }
            }



            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View();
            }
        }

        public ActionResult Delete(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "admin" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            CompetitionJudge cj = cjContext.GetDetails(id.Value);
            if (cj == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(cj);


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CompetitionJudge cj)
        {

            if (ModelState.IsValid)
            {
                if (cjContext.beforeEndDate(cj.CompetitionId) == true)
                {
                    // Delete the competition judge record from database
                    cjContext.Delete(cj.JudgeId);
                    return RedirectToAction("Index");
                }
                else
                {
                    String errorMsg = "The End Date of competition has passed. Unable to delete judge.";
                    ViewBag.validation = errorMsg;
                    return View();
                }
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View();
            }
        }


    }
}

WebAssgn_team06/Views/CompetitionJudge/Create.cshtml
@model WebAssgn_team06.Models.CompetitionJudge

@{
    ViewData["Title"] = "Assign Judge";
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Assign Judge</title>
    <style type="text/css">
        body {
            /* background-color: rgba(0, 0, 255, 0.1);*/
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }

        .btn {
            box-sizing: border-box;
            background-color: transparent;
            border: 2px solid #5D18C5;
            border-radius: 0.6em;
            color: #5D18C5;
            cursor: pointer;
            display: flex;
            align-self: center;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1;
            margin: 20px;
            padding: 1.2em 2.8em;
            text-decoration: none;
            text-align: center;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 700;
        }

            .btn:hover, .btn:focus {
                color: #000;
                outline: 0;
            }

        .third {
            border-color: #5D18C5;
            color: #fff;
            box-shadow: 0 0 40px 40px #5D18C5 inset, 0 0 0 0 #5D18C5;
            transition: all 150ms ease-in-out;
        }

            .third:hover {
                box-shadow: 0 0 10px 0 #5D18C5 inset, 0 0 10px 4px #5D18C5;
            }

        .every {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            align-items: center;
            align-content: center;
            align-self: center;
        }

        .FormContent {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
        }
    </style>
</head>
<h4 class="PageTitle">Assign Judge</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">

            <label asp-for="CompetitionId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">

                <select asp-for="CompetitionId"
                        asp-items="@(new SelectList(
                                @ViewData["CompetitionList"] as List <Competition>,
                                "CompetitionId", "CompetitionName"))"
                        class="form-control"></select>
                <span asp-validation-for="CompetitionId"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">

            <label asp-for="JudgeId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">

                <select asp-for="JudgeId"
                        asp-items="@(new SelectList(
                                @ViewData["JudgeList"] as List <Judge>,
                                "JudgeId", "JudgeName"))"
                        class="form-control"></select>
                <span asp-validation-for="JudgeId"
                      class="text-danger"></span>
            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Assign"
                       class="btn third" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <span class="text-danger">@ViewBag.validation</span>
            </div>

        </div>

    </fieldset>
</form>

WebAssgn_team06/Views/CompetitionJudge/Delete.cshtml
@model WebAssgn_team06.Models.CompetitionJudge

@{
    ViewData["Title"] = "Delete";
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Remove Judge</title>
    <style type="text/css">
        body {
            /* background-color: rgba(0, 0, 255, 0.1);*/
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }

        .btn {
            box-sizing: border-box;
            background-color: transparent;
            border: 2px solid #5D18C5;
            border-radius: 0.6em;
            color: #5D18C5;
            cursor: pointer;
            display: flex;
            align-self: center;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1;
            margin: 20px;
            padding: 1.2em 2.8em;
            text-decoration: none;
            text-align: center;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 700;
        }

            .btn:hover, .btn:focus {
                color: #000;
                outline: 0;
            }

        .third {
            border-color: #5D18C5;
            color: #fff;
            box-shadow: 0 0 40px 40px #5D18C5 inset, 0 0 0 0 #5D18C5;
            transition: all 150ms ease-in-out;
        }

            .third:hover {
                box-shadow: 0 0 10px 0 #5D18C5 inset, 0 0 10px 4px #5D18C5;
            }

        .every {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            align-items: center;
            align-content: center;
            align-self: center;
        }

        .FormContent {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
        }
    </style>
</head>
<h4 class="PageTitle">Remove Judge</h4>
<hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="CompetitionId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionId" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="JudgeId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="JudgeId" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn third" />
            </div>

        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <span class="text-danger">@ViewBag.validation</span>
            </div>

        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WebAssgn_team06/Views/CompetitionJudge/Index.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionJudge>

@{
    ViewData["Title"] = "Assign Judges";
}


@*<h4 class="PageTitle">View Judges Assigned</h4>*@
<p><a asp-action="Create">Assign Judges</a></p>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/CompetitionJudge/_ViewCompetitionJudge.cshtml" model="@Model" />

WebAssgn_team06/Views/CompetitionJudge/_ViewCompetitionJudge.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionJudge>

@if (Model.ToList().Count > 0)
{
    <style>
        .ViewBox {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
            padding: 10px;
            margin: auto;
            width: 95%;
            border-radius: 15px;
            font: Poppins;
        }

        h4 {
            left: 100px;
            position: absolute;
        }

        hr.new1 {
            border: 8px solid purple;
            width: 30px;
            left: 100px;
            position: absolute;
        }
    </style>
    <div class="ViewBox">
        <hr class="new1">
        <br />
        <br />
        <h4 class="PageTitle">View Judges Assigned</h4>
        <br />
        <br />

        <br />
        <br />
        <div class="table-responsive">
            <table id="viewStaff" class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Competition ID</th>
                        <th>Competition Name</th>
                        <th>Judge ID</th>
                        <th>Judge Name</th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.CompetitionId.ToString()</td>
                            <td>@item.CompetitionName.ToString()</td>
                            <td>@item.JudgeId.ToString()</td>
                            <td>@item.JudgeName.ToString()</td>

                            <td>


                                <a asp-action="Delete" asp-controller="CompetitionJudge"
                                   asp-route-id="@item.JudgeId">Delete</a>

                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>
        }
        else
        {
        <span style="color:red">No record found!</span>
        }