WebAssgn_team06/Controllers/CompetitionCriteriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssgn_team06.DAL;
using WebAssgn_team06.Models;

namespace WebAssgn_team06.Controllers
{   
    public class CompetitionCriteriaController : Controller
    {
        private CriteriaDAL criteriaContext = new CriteriaDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();

        public ActionResult Index(int? id)
        {

            // Stop accessing the action if not logged in
            // or account not in the "Competitor" role
            //Used for Criteria View Model
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Competitor"))
            {
                return RedirectToAction("Index", "Home");
            }
            CriteriaViewModel criteriaVM = new CriteriaViewModel();
            criteriaVM.competitionList = competitionContext.GetAllCompetition();
            // Check if CompetitionID (id) presents in the query string
            if (id != null)
            {
                ViewData["selectedCompetitionId"] = id.Value;
                // Get list of staff working in the branch
                criteriaVM.criteriaList = competitionContext.GetCompetitionCriteria(id.Value);
                int weightage = GetTotalWeightage(criteriaVM.criteriaList);
                ViewData["totalWeightage"] = weightage;
            }
            else
            {
                ViewData["selectedCompetitionId"] = "";
            }
            return View(criteriaVM);
        }

        public ActionResult Competition()
        {
            return View();
        }

        // GET: CriteriaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CriteriaController/Create
        public ActionResult Create(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Competitor" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Competitor"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["selectedCompetitionId"] = id.Value;
            ViewData["CompetitionList"] = GetCompetition();
            //ViewData["CompetitionCriteriaList"] = GetCompetitionCriteria(id);
            return View();
        }

        private List<Competition> GetCompetition()
        {
            // Get a list of competitiont from database
            List<Competition> competitionList = competitionContext.GetAllCompetition();
            // Adding a select prompt at the first row of the competition list
            competitionList.Insert(0, new Competition
            {
                CompetitionId = 0,
                CompetitionName = "--Select--"
            });
            return competitionList;
        }

        private List<Criteria> GetCompetitionCriteria(int? id)
        {
            List<Criteria> criteriaList = criteriaContext.GetAllCriteria();
            List<Criteria> competitionCriteriaList = new List<Criteria>();
            for (int i = 0; i < criteriaList.Count; i++)
            {
                if (criteriaList[i].CompetitionId == id)
                {
                    competitionCriteriaList.Add(criteriaList[i]);
                }
            }
            return competitionCriteriaList;
        }

        private int GetTotalWeightage(List<Criteria> cList)
        {
            List<int> weightage = new List<int>();
            for (int i = 0; i < cList.Count; i++)
            {
                //int weightage = 0;
                weightage.Add(cList[i].Weightage);
                int result = weightage.Sum();
                return result;
            }
            return 0;
        }

        // POST: CriteriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Criteria criteria)
        {
            // Get competition list for drop - down list
            //in case of the need to return to Create.cshtml view
            ViewData["CompetitionList"] = GetCompetition();

            if (ModelState.IsValid)
            {
                //Add criteria record to database
                criteria.CriteriaId = criteriaContext.Add(criteria);
                //Redirect user to Staff/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(criteria);
            }
        }

        // GET: CriteriaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CriteriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: CriteriaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Criteria criteria)
        {
            // Delete the criteria record from database
            criteriaContext.Delete(criteria.CriteriaId);
            return RedirectToAction("Index");
        }
    }
}

WebAssgn_team06/Views/CompetitionCriteria/Index.cshtml
@model WebAssgn_team06.Models.CriteriaViewModel

@{
    ViewData["Title"] = "Index";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login Page</title>
    <style type="text/css">
        body {
            background-color: rgba(0, 0, 255, 0.1);
            font: Poppins;
        }

        .btn {
            box-sizing: border-box;
            background-color: transparent;
            border: 2px solid #5D18C5;
            border-radius: 0.6em;
            color: #5D18C5;
            cursor: pointer;
            display: flex;
            align-self: center;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1;
            margin: 20px;
            padding: 1.2em 2.8em;
            text-decoration: none;
            text-align: center;
            text-transform: uppercase;
            font-family: 'Montserrat', sans-serif;
            font-weight: 700;
        }

            .btn:hover, .btn:focus {
                color: #000;
                outline: 0;
            }

        .third {
            border-color: #5D18C5;
            color: #fff;
            box-shadow: 0 0 40px 40px #5D18C5 inset, 0 0 0 0 #5D18C5;
            transition: all 150ms ease-in-out;
        }

            .third:hover {
                box-shadow: 0 0 10px 0 #5D18C5 inset, 0 0 10px 4px #5D18C5;
            }

        .every {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            align-items: center;
            align-content: center;
            align-self: center;
        }

        .FormContent {
            background-color: #fff;
            border-block-color: #fff;
            border-color: #fff;
            box-shadow: 2px 2px 20px grey;
        }
    </style>
</head>
<body>
    <h4 class="PageTitle">View Competition</h4>
    <!-- Display a list of competition -->
    <div class="container">
        <div class="row">
            @foreach (var item in Model.competitionList)
            {
                <div class="card" style="width:300px; margin-top:5%; margin-left:3%;">
                    <img class="card-img-top" src="~/images/competition.png" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Competition Name : @item.CompetitionName</h4>
                        <p class="card-text">
                            Area Interest: @item.AreaInterestId
                        </p>
                        <p class="card-text">
                            Start Date: @item.StartDate
                        </p>
                        <p class="card-text">
                            End Date: @item.EndDate
                        </p>
                        <p class="card-text">
                            Result Release Date : @item.ResultReleasedDate
                        </p>

                    </div>
                    <div class="card-footer">
                        <a asp-action="Index" asp-controller="CompetitionCriteria"
                           asp-route-id="@item.CompetitionId" class="btn btn-dark">View Criteria</a>
                    </div>
                </div>
                <br>
            }

        </div>
    </div>

    <!-- Display a list of criteria for each competition -->
    @if (ViewData["selectedCompetitionId"].ToString() != "")
    {
        if (Model.criteriaList.Count != 0)
        {
            <h5 id="result" style="color:red; margin-top:5%"></h5>
            <h5>
                Criteria in Competition
                @ViewData["selectedCompetitionId"].ToString() :
            </h5>

            <partial name="~/Views/CompetitionCriteria/_ViewCompetitionCriteria.cshtml"
                     model="@Model.criteriaList" />

        }
        else
        {
            <h5>No criteria for selected competition!</h5>
        }
    }
</body>
</html>

WebAssgn_team06/Views/CompetitionCriteria/_ViewCompetitionCriteria.cshtml
@model IEnumerable<WebAssgn_team06.Models.Criteria>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewCriteria" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Competition ID</th>
                    <th>Criteria Name</th>
                    <th>Weightage</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CriteriaId.ToString()</td>
                        <td>@item.CompetitionId.ToString()</td>
                        <td>@item.CriteriaName</td>
                        <td class="weightage">@item.Weightage.ToString()</td>
                    </tr>
                }
            </tbody>
        </table>

        <h5 id="result"></h5>
    </div>
    <a href="~/CompetitionSubmission/Create">Join Competition</a>
}
else
{
    <span style="color:red">No record found!</span>
}