WebAssgn_team06/Models/CompetitionScore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WebAssgn_team06.Models
{
    public class CompetitionScore
    {
        //pk, fk->  Criteria (CriteriaID)
        [Display(Name = "Criteria ID")]
        public int CriteriaId { get; set; }

        //pk, fk->  Competitor (CompetitorID)
        [Display(Name = "Competitor ID")]
        //Auto generated
        public int CompetitorId { get; set; }

        // here fk->  Competition (CompetitionID) !!!
        [Display(Name = "Competition ID")]
        public int CompetitionId { get; set; }

        //Score
        [Display(Name = "Score")]
        [Range(1, 10, ErrorMessage = "Please enter a value in between 1 and 10")]
        public int Score { get; set; }

        //DateTimeLastEdit
        //Singapore time zone
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{yyyy-mm-dd hh:mm}")]
        public DateTime DateTimeLastEdit { get; set; } = DateTime.Now;

        public string Email { get; set; }

    }
}

WebAssgn_team06/Models/CompetitionScoreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAssgn_team06.Models
{
    public class CompetitionScoreViewModel
    {
        public List<Competition> competitionList { get; set; }
        public List<CompetitionSubmission> competitionSubmissionsList { get; set; }
        public List<CompetitionScore> competitionScoreList { get; set; }

        public CompetitionScoreViewModel()
        {
            competitionList = new List<Competition>();
            competitionSubmissionsList = new List<CompetitionSubmission>();
            competitionScoreList = new List<CompetitionScore>();
        }
    }
}

WebAssgn_team06/Controllers/CompetitionScoreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssgn_team06.DAL;
using WebAssgn_team06.Models;

namespace WebAssgn_team06.Controllers
{
    public class CompetitionScoreController : Controller
    {
        private CompetitionScoreDAL competitionScoreContext = new CompetitionScoreDAL();
        private CriteriaDAL criteriaContext = new CriteriaDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private CompetitionSubmissionDAL competitionSubmissionContext = new CompetitionSubmissionDAL();
        private CompetitorDAL competitorContext = new CompetitorDAL();
        

        // GET: CompetitionScoreController
        public ActionResult Index(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            //HERE
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            CompetitionScoreViewModel competitionScoreVM = new CompetitionScoreViewModel();
            competitionScoreVM.competitionList = competitionContext.GetAllCompetition();
            if (id != null)
            {
                ViewData["selectedCompetitionId"] = id.Value;
                competitionScoreVM.competitionSubmissionsList = competitionContext.GetCompetitionSubmission(id.Value);
                HttpContext.Session.SetInt32("CompetitionId", (int)id);
            }
            else
            {
                ViewData["selectedCompetitionId"] = "";
            }

            return View(competitionScoreVM);
        }

        public ActionResult Index2(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<CompetitionScore> scoreList = competitionScoreContext.GetAllCompetitionScore();
            ViewData["selectedCompetitionId"] = id;
            if (id != null)
            {
                HttpContext.Session.SetInt32("CompetitionId", (int)id);
            }

            return View(scoreList);
        }

        public ActionResult Index3(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<CompetitionScore> scoreList = competitionScoreContext.GetAllCompetitionScore();
            ViewData["selectedCompetitionId"] = id;
            if (id != null)
            {
                HttpContext.Session.SetInt32("CompetitionId", (int)id);
            }

            return View(scoreList);
        }

        public ActionResult SubmissionScore(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            CompetitionScoreViewModel competitionScoreVM = new CompetitionScoreViewModel();
            if (id != null)
            {
                ViewData["selectedCompetitorId"] = id.Value;
                competitionScoreVM.competitionScoreList = competitionSubmissionContext.GetCompetitionSubmissionScore(id.Value);
            }
            else
            {
                ViewData["selectedCompetitorId"] = "";
            }

            return View(competitionScoreVM);
        }

        // GET: CompetitionScoreController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CompetitionScoreController/Create
        public ActionResult Create(int? id, int? compId)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            ViewData["CompetitorCriteriaList"] = GetCompetitorCriteria3(compId);
            ViewData["CompetitionId"] = compId;
            ViewData["CompetitorId"] = id;
            return View();
        }
        

        // POST: CompetitionScoreController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompetitionScore cs)
        {
            ViewData["CompetitorCriteriaList"] = GetCompetitorCriteria3(HttpContext.Session.GetInt32("CompetitionId"));
            ViewData["CompetitionId"] = HttpContext.Session.GetInt32("CompetitionId");
            if (ModelState.IsValid)
            {
                //Add competition score to database
                cs.CompetitorId = competitionScoreContext.Add(cs);
                //Redirect user to CompetitionScore/Index2 view
                return RedirectToAction("Index2");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(cs);
            }
        }


        // GET: CompetitionScoreController/Edit/5
        public ActionResult Edit(int? id, int? compId)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            CompetitionScore competitionScore = competitionScoreContext.GetDetails(id.Value,compId.Value);
            if (competitionScore == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            ViewData["CompetitorCriteriaList"] = GetCompetitorCriteria3(HttpContext.Session.GetInt32("CompetitionId"));
            //ViewData["CompetitionId"] = HttpContext.Session.GetInt32("CompetitionId");
            return View(competitionScore);
        }

        //Get all coriteria for competition
        private List<Criteria> GetCompetitorCriteria(int? id)
        {
            List<CompetitionScore> competitionScoreList = competitionScoreContext.GetAllCompetitionScore();
            List<Criteria> criteriaList = criteriaContext.GetAllCriteria();
            List<Criteria> competitorCriteriaList = new List<Criteria>();
            for (int i = 0; i < competitionScoreList.Count; i++)
            {
                if (competitionScoreList[i].CompetitorId == id)
                {
                    for (int j = 0; j < criteriaList.Count; j++)
                    {
                        if (criteriaList[j].CriteriaId == competitionScoreList[i].CriteriaId)
                        {
                            competitorCriteriaList.Add(criteriaList[j]);
                        }
                    }
                }
            }
            return competitorCriteriaList;
        }

        private List<Criteria> GetCompetitorCriteria2(int? id)
        {
            List<CompetitionScore> competitionScoreList = competitionScoreContext.GetAllCompetitionScore();
            List<Criteria> criteriaList = criteriaContext.GetAllCriteria();
            List<Criteria> competitorCriteriaList = new List<Criteria>();
            List<CompetitionSubmission> competitionSubmissionList = competitionSubmissionContext.GetAllCompetitionSubmission();
            for (int i = 0; i < competitionSubmissionList.Count; i++)
            {
                if (competitionSubmissionList[i].CompetitionId == id)
                {
                    for (int j = 0; j < criteriaList.Count; j++)
                    {
                        competitorCriteriaList.Add(criteriaList[j]);
                    }
                }
            }
            return competitorCriteriaList;
        }

        private List<Criteria> GetCompetitorCriteria3(int? id)
        {
            List<CompetitionScore> competitionScoreList = competitionScoreContext.GetAllCompetitionScore();
            List<Criteria> criteriaList = criteriaContext.GetAllCriteria();
            List<Criteria> competitorCriteriaList = new List<Criteria>();
            for (int i = 0; i < criteriaList.Count; i++)
            {
                if (criteriaList[i].CompetitionId == id)
                {
                    competitorCriteriaList.Add(criteriaList[i]);
                }
            }
            return competitorCriteriaList;
        }

        // POST: CompetitionScoreController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CompetitionScore competitionScore)
        {
            ViewData["CompetitorCriteriaList"] = GetCompetitorCriteria3(competitionScore.CompetitionId);

WebAssgn_team06/Views/CompetitionScore/Index.cshtml
@model WebAssgn_team06.Models.CompetitionScoreViewModel
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

<h4 class="PageTitle">Competition Score</h4>
<!-- Display a list of competition -->
<div class="container">
    <div class="row">
        @foreach (var item in Model.competitionList)
        {
            <div class="card" style="width:300px; margin-top:5%; margin-left:3%;">
                <img class="card-img-top" src="~/images/competition.png" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Competition Name : @item.CompetitionName</h4>
                    <p class="card-text">
                        Area Interest: @item.AreaInterestId
                    </p>
                    <p class="card-text">
                        Start Date: @item.StartDate
                    </p>
                    <p class="card-text">
                        End Date: @item.EndDate
                    </p>
                    <p class="card-text">
                        Result Release Date : @item.ResultReleasedDate
                    </p>
                </div>
                <div class="card-footer">
                    @if (item.ResultReleasedDate >= DateTime.Now)
                    {
                        <div class="container">
                            <div class="row">
                                <a asp-action="Index" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId" class="btn btn-dark">Submission</a>
                                &nbsp;
                                <a asp-action="Index2" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId" class="btn btn-dark">Score</a>
                            </div>
                        </div>
                        
                    }
                    else
                    {
                        <a asp-action="Index3" asp-controller="CompetitionScore"
                           asp-route-id="@item.CompetitionId" class="btn btn-dark">Score</a>
                    }
                </div>
            </div>
            <br>
        }

    </div>
</div>
<!-- Display a list of competition submission for each competition -->
@if (ViewData["selectedCompetitionId"].ToString() != "")
{
    if (Model.competitionSubmissionsList.Count != 0)
    {
        <h5>
            Competition submission in Competition
            @ViewData["selectedCompetitionId"].ToString() :
        </h5>
        <partial name="~/Views/CompetitionSubmission/_ViewCompetitionSubmission(Score).cshtml"
                 model="@Model.competitionSubmissionsList" />

    }
    else
    {
        <h5>No submission for selected competition!</h5>
    }
}

WebAssgn_team06/Views/CompetitionScore/Index2.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionScore>

@{
    ViewData["Title"] = "View Competition Score";
}

<h4 class="PageTitle">View Competition Score</h4>

<!-- Add a partial view to display a list of competition score records
in a tabular format. -->
<partial name="~/Views/CompetitionScore/_ViewCompetitionScore.cshtml" model="@Model" />

WebAssgn_team06/Views/CompetitionScore/Index3.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionScore>

@{
    ViewData["Title"] = "View Competition Score";
}

<h4 class="PageTitle">View Competition Score</h4>
@*<p><a asp-action="Create">Create</a></p>*@
<!-- Add a partial view to display a list of competition score records
in a tabular format. -->
<partial name="~/Views/CompetitionScore/_ViewReleaseCompetitionScore.cshtml" model="@Model" />

@*<partial name="~/Views/CompetitionSubmission/_ViewCompetitionSubmission.cshtml" model="@Model" />*@

WebAssgn_team06/Views/CompetitionScore/Index4.cshtml
@model WebAssgn_team06.Models.CompetitionScoreViewModel
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Index4";
}

<h4 class="PageTitle">Competition Score</h4>
<!-- Display a list of branches -->
<div class="table-responsive">
    <table id="viewCS" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Competition ID</th>
                <th>Competition Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Result Released Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.competitionList)
            {
                string selectedRow = "";
                if (ViewData["selectedCompetitionId"].ToString()
                == item.CompetitionId.ToString())
                {
                    // Highlight the selected row
                    selectedRow = "class='table-primary'";
                }
                <tr @Html.Raw(selectedRow)>
                    <td>@item.CompetitionId.ToString()</td>
                    <td>@item.CompetitionName</td>
                    <td>@item.StartDate</td>
                    <td>@item.EndDate</td>
                    <td>@item.ResultReleasedDate</td>
                    <td>
                        @if (item.ResultReleasedDate >= DateTime.Now)
                        {
                            <a asp-action="Index" asp-controller="CompetitionScore"
                               asp-route-id="@item.CompetitionId">View Submission</a>
                            <br />
                            <a asp-action="Index2" asp-controller="CompetitionScore"
                               asp-route-id="@item.CompetitionId">View Score</a>
                        }
                        else
                        {
                            <a asp-action="Index3" asp-controller="CompetitionScore"
                               asp-route-id="@item.CompetitionId">View Score</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Display a list of staff members for each branch -->
@if (ViewData["selectedCompetitionId"].ToString() != "")
{
    if (Model.competitionSubmissionsList.Count != 0)
    {
        <h5>
            Competition submission in Competition
            @ViewData["selectedCompetitionId"].ToString() :
        </h5>
        <partial name="~/Views/CompetitionSubmission/_ViewCSCompetitorScore.cshtml"
                 model="@Model.competitionSubmissionsList" />

    }
    else
    {
        <h5>No submission for selected competition!</h5>
    }
}

WebAssgn_team06/Views/CompetitionScore/IndexCompetitor.cshtml
@model WebAssgn_team06.Models.CompetitionScoreViewModel
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

<h4 class="PageTitle">Competition Score</h4>
<!-- Display a list of competition -->
<div class="container">
    <div class="row">
        @foreach (var item in Model.competitionList)
        {
            <div class="card" style="width:300px; margin-top:5%; margin-left:3%;">
                <img class="card-img-top" src="~/images/competition.png" alt="Card image" style="width:100%">
                <div class="card-body">
                    <h4 class="card-title">Competition Name : @item.CompetitionName</h4>
                    <p class="card-text">
                        Area Interest: @item.AreaInterestId
                    </p>
                    <p class="card-text">
                        Start Date: @item.StartDate
                    </p>
                    <p class="card-text">
                        End Date: @item.EndDate
                    </p>
                    <p class="card-text">
                        Result Release Date : @item.ResultReleasedDate
                    </p>
                </div>
                <div class="card-footer">
                    @if (item.ResultReleasedDate >= DateTime.Now)
                    {
                        <div class="container">
                            <div class="row">
                                @*<a asp-action="IndexCompetitor" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId" class="btn btn-dark">Submission</a>
                                &nbsp;*@
                                @*<a asp-action="IndexCompetitor3" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId" class="btn btn-dark">Score</a>*@
                            </div>
                        </div>

                    }
                    else
                    {
                        <a asp-action="IndexCompetitor2" asp-controller="CompetitionScore"
                           asp-route-id="@item.CompetitionId" class="btn btn-dark">Score</a>
                    }
                </div>
            </div>
            <br>
        }

    </div>
</div>


@*<div class="table-responsive">
        <table id="viewCS" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Competition ID</th>
                    <th>Competition Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Result Released Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.competitionList)
                {
                    string selectedRow = "";
                    if (ViewData["selectedCompetitionId"].ToString()
                    == item.CompetitionId.ToString())
                    {
                        // Highlight the selected row
                        selectedRow = "class='table-primary'";
                    }
                    <tr @Html.Raw(selectedRow)>
                        <td>@item.CompetitionId.ToString()</td>
                        <td>@item.CompetitionName</td>
                        <td>@item.StartDate</td>
                        <td>@item.EndDate</td>
                        <td>@item.ResultReleasedDate</td>
                        <td>
                            @if (item.ResultReleasedDate >= DateTime.Now)
                            {
                                <a asp-action="Index" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId">View Submission</a>
                                <br />
                                <a asp-action="Index2" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId">View Score</a>
                            }
                            else
                            {
                                <a asp-action="Index3" asp-controller="CompetitionScore"
                                   asp-route-id="@item.CompetitionId">View Score</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>*@
<!-- Display a list of staff members for each branch -->
@if (ViewData["selectedCompetitionId"].ToString() != "")
{
    if (Model.competitionSubmissionsList.Count != 0)
    {
        <h5>
            Competition submission in Competition
            @ViewData["selectedCompetitionId"].ToString() :
        </h5>
        <partial name="~/Views/CompetitionSubmission/_ViewCompetitionSubmission(Score).cshtml"
                 model="@Model.competitionSubmissionsList" />

    }
    else
    {
        <h5>No submission for selected competition!</h5>
    }
}

WebAssgn_team06/Views/CompetitionScore/IndexCompetitor2.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionScore>

@{
    ViewData["Title"] = "View Competition Score";
}

<h4 class="PageTitle">View Competition Score</h4>
@*<p><a asp-action="Create">Create</a></p>*@
<!-- Add a partial view to display a list of competition score records
in a tabular format. -->
<partial name="~/Views/CompetitionScore/_ViewCompetitorScore.cshtml" model="@Model" />

@*<partial name="~/Views/CompetitionSubmission/_ViewCompetitionSubmission.cshtml" model="@Model" />*@

WebAssgn_team06/Views/CompetitionScore/_ViewCompetitionScore.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionScore>

@if (Model.ToList().Count > 0)
{
    @*@foreach (var item in Model)
    {*@
        
            <div class="table-responsive">
                <table id="viewCompetitionScore" class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>CriteriaID</th>
                            <th>CompetitorID</th>
                            <th>CompetitionID</th>
                            <th>Score</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (Context.Session.GetInt32("CompetitionId") == item.CompetitionId)
                            {
                                <tr>
                                    <td>@item.CriteriaId.ToString()</td>
                                    <td>@item.CompetitorId.ToString()</td>
                                    <td>@item.CompetitionId.ToString()</td>
                                    <td>@item.Score.ToString()</td>
                                    <td>
                                        <a asp-action="Edit" asp-controller="CompetitionScore"
                                           asp-route-id="@item.CompetitorId" asp-route-CompId="@item.CompetitionId">Edit</a> |
                                    </td>
                                </tr>
                            }  
                        }
                    </tbody>
                </table>
            </div>    
}
else
{
    <span style="color:red">No record found!</span>
}

WebAssgn_team06/Views/CompetitionScore/_ViewCompetitorScore.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionScore>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewCompetitionScore" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>CriteriaID</th>
                    <th>CompetitorID</th>
                    <th>CompetitionID</th>
                    <th>Score</th>
                    <th>Email</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    @if (Context.Session.GetString("LoginID") == item.Email.ToString())
                    {

                    @*//if (ViewData["selectedCompetitorId"].ToString() == item.CompetitorId.ToString())
                        //{*@
                <tr>
                    <td>@item.CriteriaId.ToString()</td>
                    <td>@item.CompetitorId.ToString()</td>
                    <td>@item.CompetitionId.ToString()</td>
                    <td>@item.Score.ToString()</td>
                    <td>@item.Email.ToString()</td>
                    <td>
                        @*<a asp-action="Delete" asp-controller="CompetitionScore"
            asp-route-id="@item.CompetitorId">Appeal</a>*@
                        <a href="~\CompetitionSubmission\Edit.cshtml">Appeal</a>
                        @* Create a Appeal View to send appeal form *@
                    </td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}
@*<!DOCTYPE html>
<html>
<head>
    <title>View Score</title>
    <style>
        body {
            font-family: arial;
            margin: 30px;
        }

        input {
            display: block;
            padding: 10px;
            font-size: 14pt;
            margin-top: 20px;
            margin-bottom: 20px;
            float: left;
        }

        button {
            padding: 12px;
            font-size: 14pt;
            margin-top: 20px;
            margin-bottom: 20px;
            margin-left: 20px;
        }
    </style>
</head>
<body>
    <div id="story"></div>

    <input id="answerField" name="number" placeholder="Answer Here" />
    <button id="javascriptButton">Submit Answer</button>
    <script>
        // 
        function updateStory() {
            var finalAnswer = storyOutput;
            document.getElementById('story').innerHTML = finalAnswer;
        };

        // 
        var storyOutput = "Hey! This is an interactive story. Do you want to take part?";
        updateStory();

        //
        document.getElementById('javascriptButton').onclick = function interpretAnswer() {
            var inputResults = document.getElementById('answerField').value;
            answer = inputResults.toUpperCase();
            checkAnswer();
        };

        //
        function checkAnswer() {
            if (answer === "YES") {
                storyOutput = "Excellent!";
            }
            else if (answer === "CAN I THINK ABOUT IT?") {
                storyOutput = "Sure! Type something else in whenever you're ready.";
            }
            else if (answer === "1") {
                storyOutput = "Sure! Type something else in whenever you're ready.";
            }
            else if (answer === 'NO') {
                storyOutput = "Aw! Okay. See you later.";
            }
            else {
                // With no results, or bad results, repeat the question with more detail:
                storyOutput = "Hey! This is an interactive story. Do you want to take part? YES or NO";
            };
            updateStory();
        }
    </script>
</body>
</html>*@

WebAssgn_team06/Views/CompetitionScore/_ViewReleaseCompetitionScore.cshtml
@model IEnumerable<WebAssgn_team06.Models.CompetitionScore>

@if (Model.ToList().Count > 0)
{
    @*@foreach (var item in Model)
    {*@
        
            <div class="table-responsive">
                <table id="viewCompetitionScore" class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>CriteriaID</th>
                            <th>CompetitorID</th>
                            <th>CompetitionID</th>
                            <th>Score</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (Context.Session.GetInt32("CompetitionId") == item.CompetitionId)
                            {
                                @*//if (ViewData["selectedCompetitorId"].ToString() == item.CompetitorId.ToString())
                                //{*@
                                <tr>
                                    <td>@item.CriteriaId.ToString()</td>
                                    <td>@item.CompetitorId.ToString()</td>
                                    <td>@item.CompetitionId.ToString()</td>
                                    <td>@item.Score.ToString()</td>
                                    <td>
                                        <a asp-action="Delete" asp-controller="CompetitionScore"
                                           asp-route-id="@item.CompetitorId">Delete</a>
                                    </td>
                                </tr>
                            }
                           
                        }


                    </tbody>
                </table>
            </div>

        
    
}
else
{
    <span style="color:red">No record found!</span>
}